spring.application.name=payment-system-backend

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/payment_system_backend
spring.datasource.username=root
spring.datasource.password=Anshu@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true